vich_uploader:
    db_driver: orm

    mappings:
        medias:
            uri_prefix: /images/medias
            upload_destination: '%kernel.project_dir%/public/images/medias'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
